version: '3.6'

services:
    guibuilderm:
        restart: always
        image: bcbdockerdevreg.mdanderson.edu:5443/qcprludev07/guibuilder:2.21.0
        hostname: guibuilderm
        ports:
          - "8080:8080"
        networks:
          - guibuilder
        volumes:
          - /docker_data/NG-CHM_GUI_BUILDER/logs:/usr/local/tomcat/logs
          - /docker_data/NG-CHM_GUI_BUILDER/map_build_dir:/usr/local/tomcat/webapps/NGCHM-web-builder/MapBuildDir

networks:
    guibuilder:
        external: true

