services:
    guibuilderm:
        restart: always
        image: ${REGNAME:-ngchm/builder}:${TAGNAME:-latest}
        build:
            context: ./build
            args:
                - VIEWER_REPO=${VIEWER_REPO:-https://github.com/MD-Anderson-Bioinformatics/NG-CHM-Artifacts}
                - VIEWER_TAG=${VIEWER_TAG:-2.23.3-build-7}
        hostname: guibuilderm
        ports:
            - "${PORT:-8080}:8080"
        networks:
            - guibuilder
        volumes:
            - ${LOGDIR:-./builder_data/logs}:/usr/local/tomcat/logs
            - ${BUILDDIR:-./builder_data/map_build_dir}:/usr/local/tomcat/webapps/NGCHM-web-builder/MapBuildDir

networks:
    guibuilder:
        external: true

